### ISSUE TITLE
Needs workspace administrator information on some of the channels

### ISSUE THREAD

**Issue by nchetan-zz** [thisdot/tech-community-slacks#215]
When trying to create accounts in some of the spaces, they need "workspace administrator" invitation. I couldn't find a quick way to find this information for some of the channels (one e.g. https://techseattle.slack.com/?redir=%2Fmessages%2FC045K4QLR%2F)

Would it be possible to get this information added (may be slowly added over period of time)?

**Comment by jdwilkin4** [comment]
Thank you for bringing up this issue. 
We are currently in the process of updating this repo but I don't think there is a good way to add this information on our ends. We might just have to remove those entries from the list.
