### ISSUE TITLE
Any interest in adding Discord servers too?

### ISSUE THREAD

**Issue by stephencweiss** [thisdot/tech-community-slacks#230]
First: I love this resource! Thank you for compiling it! 

Wondering if it makes sense to think of this as Tech Communities and expand from there. For example, I have found that a number of communities migrated from Slack to Discord over the past couple of years, so I could see listing those too.

Additionally, there are online communities that might deserve a mention (e.g., Dev.To)

Happy to make a PR if you're interested. Otherwise, if not, I may create a similar repo and reference this one as inspiration / back link so that folks can find the "full universe" (or as far as we know of it 😄 ) of tech communities.

Cheers!

**Comment by joshua-bn** [comment]
@stephencweiss did you ever create that list?

**Comment by jdwilkin4** [comment]
HI @stephencweiss ! 

Thank you for creating this issue.

We are currently focused on just slack groups right now.
