### ISSUE TITLE
Remove Boston JavaScript from list since link no longer works

### ISSUE THREAD

**Issue by jdwilkin4** [thisdot/tech-community-slacks#254]
The invite link that was provided for this slack group no longer works.
Let's remove it from the list since people can't join the group.

If you are interested in working on this issue, please comment below and it will be assigned to you.

**Comment by VividhPandey003** [comment]
Hey, I am a beginner to Open Source and really looking forward to contribute to this repo. Could you please explain this issue to me and if I'm able to, assign this issue to me

**Comment by jdwilkin4** [comment]
HI @VividhPandey003 ! 

In our README, there is a list of tech community slack groups arranged by country. For the New England category, there is a group called Boston JavaScript but the link no longer works. So that slack group will need to be removed.

Here is the readme file that needs to be edited. 
https://github.com/thisdot/tech-community-slacks/blob/master/README.md#new-england

I would also suggest reading through the contributing guide which walks you through how to create a pull request.
https://github.com/thisdot/tech-community-slacks/blob/master/CONTRIBUTING.md

Are you interested in working on this issue?

**Comment by VividhPandey003** [comment]
Hii, Thanks for replying. This seems to be a really easy issue. I can surely do it.[removing a link from a readme file]. 
One doubt ma'am, since this is just a readme correction, are there chances that it gets considered in Hacktoberfest Spam. 
If yes, then I'll make a PR now itself, otherwise I'll wait till Oct 1 for it to be considered in my Hacktoberfest PRs

**Comment by VividhPandey003** [comment]
> I removed the Hacktoberfest label for this issue since Hacktoberfest has created stricter rules this year for what counts.
> 
> I will add more issues, about adding new content which won't be considered spam and will count for Hacktoberfest.

Yes, Thank you 😄

**Comment by VividhPandey003** [comment]
Hey @jdwilkin4 , I have made a Pull Request for the same. 
[Pull Request Link](https://github.com/thisdot/tech-community-slacks/pull/262)
