### ISSUE TITLE
Add more slack groups for the public slack conference community section

### ISSUE THREAD

**Issue by jdwilkin4** [thisdot/tech-community-slacks#261]
We could use some more slack groups in these areas.

If you are new to this repository, please read through the [contributing documentation](https://github.com/thisdot/tech-community-slacks/blob/master/CONTRIBUTING.md).

**Please note: if you are planning on creating a PR and have it count for hacktoberfest, all PR's must be merged during the month of October only. Any PR's merged before or after October will not count towards hacktoberfest**

We are going to leave this issue open for anyone to contribute to and add their slack group suggestions.

**Comment by KiranSatyaRaj** [comment]
there are some slack channels that I'm a part of like cloud native foundation, and tools around it, few other open source channels, Can you assign this issue to me? @jdwilkin4

**Comment by jdwilkin4** [comment]
Hi @KiranSatyaRaj ! 

We are going to leave this issue open for anyone to contribute to and add their slack group suggestions.
You are free to create a PR 👍

**Comment by KiranSatyaRaj** [comment]
#265 
Hey @jdwilkin4 , I made a pull request and referenced it to this issue, please check if it is eligible to merge
