### ISSUE TITLE
Vancouver tech link is broken

### ISSUE THREAD

**Issue by rahulr8** [thisdot/tech-community-slacks#270]
Vancouver (canada) link does not work anymore. Just the Heroku app is down or does the Slack channel not exist anymore?

**Comment by jdwilkin4** [comment]
HI @rahulr8 ! 

Thank you for bringing this to our attention.
I haven't been able to find a replacement link, so I think it is best to remove that link from the list.

I will open this issue up to anyone interested in contributing.
No need to ask to be assigned.
Read through the contributing docs and create a PR if you are interested in fixing this issue. 

You will need to remove the [Vancouver Developers (YVR Dev)](https://yvrdev.herokuapp.com/) link from the README.

**Comment by shraddha761** [comment]
Hye 
I update the changes but unable to push it in the remote branch. As I am a beginner to open source please give some guidance regrading pushing the changes to remote branch
